import Providers from "./Redux/Provider";

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

import "bootstrap/dist/css/bootstrap.css";
import Header from "./component/Header";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <div className="album py-5 bg-body-tertiary">
            <div className="container">
              <Header />
              {children}
            </div>
          </div>
        </body>
      </html>
    </Providers>
  );
}
